dist: bionic
language: java
before_install:
- rm ~/.m2/settings.xml
jdk:
- openjdk11
install: ./mvnw -v
script: ./mvnw -B -nsu verify jacoco:report
cache:
  directories:
  - "$HOME/.m2"
branches:
  except:
  - "/^release\\/.*$/"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: JK5sJOXPiHro/BiBrgAk8R1hxkKf4YN7lLWg/Pk/BnFDZGHmZ9EZqVlHHvZD/TMjyeYT51042TtMQgS1OQtSvy3fSQsvga/cxtoxI2trnIBS19E/QPAcFB7UX1oAviLa8Xjzuacwf6XtdM9MOuiK7E/ytb82Ac9A92IODdRZC+tkpog56ys+DrDcp0KWbqukAqIki36fvy0aG05FYTTvyDUfzpeQWHnOu9owVo3PEHQqmw61GiD7QbA4JWB7ivcnKEs9D2yU8WR7MVT5yfCF6m+i8gj9TqS3jW0brNDfigLjdYE0UrgSQBmnoNDBWb0pFOcFmMlETLBxVSOlheQqpFIgi+Tnp9aPXwTIHc4i5McVpUz9vM0piW3yfHzI5Am9yqYHng54hYd2bW2/hdWJ42Y8gvoUpix/mF/fc+beZjC07451RyNMHQAyli9vlc4G2Z3W9Q2rWfudV3gxgXf5eIXLfv4EQeEV9346n68rAz9D2SsQDlNETlS3tep8wGocI0f2jC0zWW84Ssesu6mOqseLn0GvtJZxMOjumee2WhFsvRTwrYa/sOnrwcERzOiotjURBtH0uw8DsKIqy272Fs2GTFsnl3UtSLAN1+Pm7SlG82C3TWRpoOSXQYxfhrAHdWcZhz0kiVLTsUnateSOdxtR+8FpJXt1PIV8KYp/eH0=
